engine=Python
option.entryPoint=model
option.model_id=hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4
option.task=text-generation
option.tensor_parallel_degree=1
option.pipeline_parallel_degree=1
option.max_model_len=2048
option.rolling_batch=disable
option.enable_lora=true
option.max_loras=3
option.max_lora_rank=16
option.max_cpu_loras=3
option.gpu_memory_utilization=0.90
option.trust_remote_code=true
option.enforce_eager=false
option.predict_timeout=300
